version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=andrey
      - MYSQL_PASSWORD=3221
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=yes